name: CI

on:
  push:
    branches: [ master ] 
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Docker Login
        uses: docker/login-action@v1.8.0
        with:
         username: heremoryoo
         password: ${{ secrets.DOCKER_TOKEN }}
         logout: true

      - name: Build Images
        env:
          OLS_VERSION: 1.6.19
          OLS_VERSION2: 1.7.8
          OLS_VERSION3: 1.7.9
          OLS_VERSION4: 1.6.20
          PHP_VERSION: lsphp73
          PHP_VERSION2: lsphp74
          PHP_VERSION3: lsphp72
        run: |
          cd template && ./build.sh --ols $OLS_VERSION --php $PHP_VERSION && \
          ./build.sh --ols $OLS_VERSION --php $PHP_VERSION2 && \
          ./build.sh --ols $OLS_VERSION --php $PHP_VERSION3 && \
          ./build.sh --ols $OLS_VERSION2 --php $PHP_VERSION && \
          ./build.sh --ols $OLS_VERSION2 --php $PHP_VERSION2 && \
          ./build.sh --ols $OLS_VERSION2 --php $PHP_VERSION3 && \
          ./build.sh --ols $OLS_VERSION3 --php $PHP_VERSION && \
          ./build.sh --ols $OLS_VERSION3 --php $PHP_VERSION2 && \
          ./build.sh --ols $OLS_VERSION3 --php $PHP_VERSION3 && \
          ./build.sh --ols $OLS_VERSION4 --php $PHP_VERSION && \
          ./build.sh --ols $OLS_VERSION4 --php $PHP_VERSION2 && \
          ./build.sh --ols $OLS_VERSION4 --php $PHP_VERSION3 && \
