name: CI

on:
  push:
    branches: [ master ] 
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Docker Login
        uses: docker/login-action@v1.8.0
        with:
         username: heremoryoo
         password: ${{ secrets.DOCKER_TOKEN }}
         logout: true

      - name: Build Images
        env:
          OLS_VERSION: 1.6.19 1.7.8
          PHP_VERSION: lsphp73 lsphp74 
        run: |
          cd template && ./build.sh --ols $OLS_VERSION --php $PHP_VERSION
